//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRPManagerBot.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFRPManagerBot.Core.CommandsStrings", typeof(CommandsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemaster link to the session:.
        /// </summary>
        public static string LinkToSessionGameMaster {
            get {
                return ResourceManager.GetString("LinkToSessionGameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the session:.
        /// </summary>
        public static string LinkToSessionPlayer {
            get {
                return ResourceManager.GetString("LinkToSessionPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a session signup started! Start one with the &apos;session signup&apos; command..
        /// </summary>
        public static string SessionSignupNotStarted {
            get {
                return ResourceManager.GetString("SessionSignupNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a singup started! Start the session with the &apos;session start&apos; command..
        /// </summary>
        public static string SessionSignupStarted {
            get {
                return ResourceManager.GetString("SessionSignupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wants to start a session!.
        /// </summary>
        public static string WantsToStart {
            get {
                return ResourceManager.GetString("WantsToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the session starts, everyone who signed up will get a link to it..
        /// </summary>
        public static string WantsToStartDescription {
            get {
                return ResourceManager.GetString("WantsToStartDescription", resourceCulture);
            }
        }
    }
}
